name: Build and Push to GHCR

on:
  push:
    tags:
      - 'release-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        run: |
          RAW_TAG=${GITHUB_REF#refs/tags/}
          VERSION=${RAW_TAG#release-}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')
          docker build -t $IMAGE_NAME_LOWER .
          echo "IMAGE_NAME=$IMAGE_NAME_LOWER" >> $GITHUB_ENV

      - name: Push image
        run: |
          docker push ${{ env.IMAGE_NAME }}
